#Will determine if DBUtilities will use an databse connection for storing its data, or an file system
UseSQL: true

#you're sql server settings
SQL_USER: "root"
SQL_PASSWORD: ""
SQL_HOST: "localhost"
SQL_PORT: 3306
SQL_DATABASE: "DBUtil"
SQL_USE_SLL: true


#This is where you put you're bot-token in
#Be sure only you know about you're bot-token, and never never show it to anyone else
Token: ""

#If the DataBaseConnector will log to an file, can be usefully for debugging
logDBToFile: true

#file version of the config.yml
#dont change, but if changed, not a big problem, all you're configs will be backuped
VERSION: "2.0.0 Beta b5"